// categories.js
const categories = {
    html: "HTML",
    css: "CSS",
    javascript: "JavaScript",
    react: "React",
    vue: "Vue.js",
    angular: "Angular",
    nodejs: "Node.js",
    python: "Python",
    java: "Java",
    csharp: "C#",
    php: "PHP",
    ruby: "Ruby",
    swift: "Swift",
    kotlin: "Kotlin",
    sql: "SQL",
    mongodb: "MongoDB",
    firebase: "Firebase",
    aws: "AWS",
    azure: "Azure",
    gcp: "Google Cloud Platform",
    devops: "DevOps",
    docker: "Docker",
    kubernetes: "Kubernetes",
    machineLearning: "Machine Learning",
    dataScience: "Data Science",
    cybersecurity: "Cybersecurity",
    blockchain: "Blockchain",
    uxDesign: "UX Design",
    uiDesign: "UI Design",
    mobileDevelopment: "Mobile Development",
    gameDevelopment: "Game Development",
    projectManagement: "Project Management",
    agile: "Agile",
    scrum: "Scrum",
    businessAnalysis: "Business Analysis",
    digitalMarketing: "Digital Marketing",
    seo: "SEO",
    contentWriting: "Content Writing",
    entrepreneurship: "Entrepreneurship"
  };
  
  export default categories;
  